import type { Metadata, Viewport } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import WhatsAppFAB from "@/components/WhatsAppFAB";
import PWAInstallPrompt from "@/components/PWAInstallPrompt";
import PwaInstallButton from "@/components/PwaInstallButton";
import ShareSidebar from "@/components/ShareSidebar";
import RegisterSW from "@/components/RegisterSW";
import SkipLink from "@/components/SkipLink";
import SiteChrome from "@/components/SiteChrome";
import NextTopLoader from "nextjs-toploader";
import DialogHost from "@/components/ui/Dialog";
import ToastHost from "@/components/ui/Toast";
import JsonLd from "@/components/JsonLd";
import {
  organizationSchema,
  websiteSchema,
  localBusinessSchema,
} from "@/lib/schema";
import { getSiteUrl, absoluteUrl } from "@/lib/site-url";

const bn = Noto_Sans_Bengali({
  variable: "--font-bn",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  preload: true,
});

const SITE_URL = getSiteUrl();
const OG_IMAGE = absoluteUrl("/og-image.jpg");

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Promise Proper Development Ltd. — স্বপ্ন যেখানে বাস্তব",
    template: "%s · PromisePD",
  },
  description:
    "ঢাকার বিশ্বস্ত আবাসন অংশীদার। প্রিমিয়াম আবাসিক ও বাণিজ্যিক প্রকল্প, নমনীয় কিস্তি, আইনি নিরাপত্তা এবং ১৫+ বছরের অভিজ্ঞতা।",
  applicationName: "PromisePD",
  keywords: [
    "PromisePD",
    "Promise City",
    "প্রমিস সিটি",
    "প্রমিস পিপিডি",
    "Real Estate Dhaka",
    "ঢাকা রিয়েল এস্টেট",
    "ফুজালা টাওয়ার",
    "ফুজালা কমপ্লেক্স",
    "আহবাব প্যালেস",
    "Ahbab Real Estate",
    "Promise International",
    "Ahbab Travels Tours",
    "Hajj Umrah Bangladesh",
    "Interior 3D Design Dhaka",
    "Apartment Dhaka",
    "জমি বিক্রয় ঢাকা",
  ],
  authors: [{ name: "Promise Proper Development Ltd.", url: SITE_URL }],
  creator: "Promise Proper Development Ltd.",
  publisher: "Promise Proper Development Ltd.",
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // Replace these placeholders once GSC / Bing verification codes are issued.
  verification: {
    google: "NkITNKPeTvXuOKX7wA6wttEgfSiT60fXf68MwbpqfOA",
    other: { "msvalidate.01": [] },
  },
  category: "Real Estate",
  openGraph: {
    type: "website",
    locale: "bn_BD",
    url: SITE_URL,
    title: "Promise Proper Development Ltd. — স্বপ্ন যেখানে বাস্তব",
    description:
      "ঢাকার বিশ্বস্ত আবাসন অংশীদার। ৫টি বিভাগে এক ছাদের নিচে সম্পূর্ণ সমাধান।",
    siteName: "PromisePD",
    images: [
      {
        url: OG_IMAGE,
        secureUrl: OG_IMAGE,
        type: "image/jpeg",
        width: 1200,
        height: 630,
        alt: "PromisePD — স্বপ্ন যেখানে বাস্তব",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@promisepd",
    creator: "@promisepd",
    title: "Promise Proper Development Ltd.",
    description: "স্বপ্ন যেখানে বাস্তব · ঢাকার বিশ্বস্ত আবাসন অংশীদার।",
    images: [{ url: OG_IMAGE, alt: "PromisePD" }],
  },
  appleWebApp: {
    capable: true,
    title: "PromisePD",
    statusBarStyle: "default",
    // Branded iOS launch screens (logo on white).  iOS only honours an
    // image whose media query matches the device EXACTLY, so one entry per
    // common iPhone resolution.  Generated by scripts/gen-pwa-assets.mjs.
    startupImage: [
      { url: "/splash/apple-splash-640x1136.png", media: "(device-width:320px) and (device-height:568px) and (-webkit-device-pixel-ratio:2) and (orientation:portrait)" },
      { url: "/splash/apple-splash-750x1334.png", media: "(device-width:375px) and (device-height:667px) and (-webkit-device-pixel-ratio:2) and (orientation:portrait)" },
      { url: "/splash/apple-splash-828x1792.png", media: "(device-width:414px) and (device-height:896px) and (-webkit-device-pixel-ratio:2) and (orientation:portrait)" },
      { url: "/splash/apple-splash-1125x2436.png", media: "(device-width:375px) and (device-height:812px) and (-webkit-device-pixel-ratio:3) and (orientation:portrait)" },
      { url: "/splash/apple-splash-1170x2532.png", media: "(device-width:390px) and (device-height:844px) and (-webkit-device-pixel-ratio:3) and (orientation:portrait)" },
      { url: "/splash/apple-splash-1179x2556.png", media: "(device-width:393px) and (device-height:852px) and (-webkit-device-pixel-ratio:3) and (orientation:portrait)" },
      { url: "/splash/apple-splash-1242x2688.png", media: "(device-width:414px) and (device-height:896px) and (-webkit-device-pixel-ratio:3) and (orientation:portrait)" },
      { url: "/splash/apple-splash-1284x2778.png", media: "(device-width:428px) and (device-height:926px) and (-webkit-device-pixel-ratio:3) and (orientation:portrait)" },
      { url: "/splash/apple-splash-1290x2796.png", media: "(device-width:430px) and (device-height:932px) and (-webkit-device-pixel-ratio:3) and (orientation:portrait)" },
    ],
  },
  // icons intentionally omitted — Next.js auto-discovers src/app/icon.png
  // and src/app/apple-icon.png (cropped to the PPD mark for crisp rendering
  // at favicon sizes).
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="bn" className={bn.variable} suppressHydrationWarning>
      <head>
        {/* No preconnect to api.dicebear.com — avatars from it don't appear
            above the fold on the public pages, so PageSpeed flagged it as an
            unused preconnect. They still load fine on demand where used. */}
        {/* Site-wide structured data (Organization, WebSite, LocalBusiness). */}
        <JsonLd data={organizationSchema()} />
        <JsonLd data={websiteSchema()} />
        <JsonLd data={localBusinessSchema()} />
        {/* Footer + FABs stay on the website but disappear inside the installed
            PWA so it feels native. Raw <style> on purpose: Tailwind v4's
            Lightning CSS drops this rule if it lives in globals.css. */}
        {/* Light / dark: re-apply the saved choice BEFORE first paint so a
            dark visitor never sees a white flash. Pairs with ThemeToggle. */}
        <Script id="theme-init" strategy="beforeInteractive">
          {"(function(){try{if(localStorage.getItem('pc-theme')==='dark')document.documentElement.setAttribute('data-theme','dark')}catch(e){}})();"}
        </Script>
        <style
          dangerouslySetInnerHTML={{
            __html: [
              // ── Dark theme ──────────────────────────────────────────────
              // Every utility built on the brand tokens (bg-bg, text-fg,
              // border-border, bg-brand-blue-tint …) flips through these
              // variables; the few hard-coded whites / tints below are
              // remapped so cards, pills and soft badges stay readable.
              "html[data-theme=dark]{color-scheme:dark;--color-bg:#0b1220;--color-bg-soft:#111a2e;--color-bg-soft-2:#16213a;--color-fg:#e8edf7;--color-fg-soft:#c9d2e6;--color-fg-muted:#94a0b8;--color-fg-faint:#7c879c;--color-border:#223052;--color-border-strong:#2c3b63;--color-brand-blue-tint:#1b2d55;--color-brand-red-tint:#3a1a24;--color-brand-ash-tint:#1a2338;--color-brand-ash-soft:#2a3550;--shadow-card:0 2px 14px -4px rgba(0,0,0,.5);scrollbar-color:#3463c7 #111a2e}html[data-theme=dark] .glass,html[data-theme=dark] .glass-strong{background:rgba(17,26,46,.75)!important;border-color:rgba(255,255,255,.08)!important}",
              "html[data-theme=dark] .bg-white{background-color:var(--color-bg-soft)!important}",
              "html[data-theme=dark] .bg-white\\/95,html[data-theme=dark] .bg-white\\/90,html[data-theme=dark] .bg-white\\/80,html[data-theme=dark] .bg-white\\/70,html[data-theme=dark] .bg-white\\/60{background-color:rgba(17,26,46,.92)!important}",
              "html[data-theme=dark] .bg-emerald-50{background-color:rgba(16,185,129,.14)!important}html[data-theme=dark] .bg-amber-50{background-color:rgba(245,158,11,.14)!important}html[data-theme=dark] .bg-violet-50{background-color:rgba(139,92,246,.16)!important}",
              "html[data-theme=dark] .text-emerald-700{color:#34d399!important}html[data-theme=dark] .text-amber-700,html[data-theme=dark] .text-amber-800{color:#fbbf24!important}html[data-theme=dark] .text-brand-blue-dark{color:#8fb0f5!important}html[data-theme=dark] .text-brand-red-dark{color:#ff6b74!important}",
              // image scrims / backdrops that were built from the (now light) fg colour stay dark
              "html[data-theme=dark] .from-fg\\/85{--tw-gradient-from:rgba(11,18,32,.85)}html[data-theme=dark] .via-fg\\/25{--tw-gradient-via:rgba(11,18,32,.25)}html[data-theme=dark] .bg-fg\\/30{background-color:rgba(0,0,0,.6)!important}",
              "html[data-theme=dark] img.mix-blend-multiply{mix-blend-mode:screen}",
              "html[data-theme=dark] .bg-white\\/92,html[data-theme=dark] .bg-white\\/75{background-color:rgba(17,26,46,.9)!important}html[data-theme=dark] .bg-\\[\\#fff7e6\\]{background-color:rgba(245,158,11,.16)!important}",
              "html[data-theme=dark] .bg-emerald-100{background-color:rgba(16,185,129,.2)!important}html[data-theme=dark] .bg-amber-100{background-color:rgba(245,158,11,.2)!important}html[data-theme=dark] .text-emerald-800{color:#34d399!important}html[data-theme=dark] .text-violet-700{color:#c4b5fd!important}",
              "html[data-theme=dark] .to-white{--tw-gradient-to:var(--color-bg)}html[data-theme=dark] .via-white\\/30{--tw-gradient-via:rgba(11,18,32,.3)}html[data-theme=dark] .from-white\\/40{--tw-gradient-from:rgba(255,255,255,.08)}",
              // Footer + FABs disappear inside the installed PWA.
              "@media all and (display-mode:standalone){.pwa-hide{display:none!important}}",
              // Mobile performance: freeze the always-running decorative
              // animations on phones (blobs, gradient shimmer, button shine).
              "@media (max-width:768px){.animate-blob,.text-grad,.btn-shine::after,.grad-border::before{animation:none!important}}",
              // Clip horizontal overflow with `clip` (not `hidden`) so html/body
              // never become a scroll container — otherwise `overflow-y` computes
              // to `auto` and `position: sticky` descendants (the investor
              // portal's pinned header) silently stop sticking.  Raw <style> on
              // purpose: Lightning CSS drops this when written in globals.css.
              "@supports (overflow:clip){html,body{overflow-x:clip!important}}",
              // /account (investor portal) in the BROWSER: clear the fixed
              // navbar and dock the sticky header just below it.
              ".acct-shell{padding-top:5.25rem}@media(min-width:640px){.acct-shell{padding-top:6rem}}",
              ".acct-sticky{top:76px}@media(min-width:640px){.acct-sticky{top:84px}}",
              // …but inside the installed PWA the chrome is hidden, so the
              // portal starts at the very top (no navbar to clear) — native feel.
              "@media all and (display-mode:standalone){.acct-shell{padding-top:1rem}.acct-sticky{top:0}}",
            ].join(""),
          }}
        />
      </head>
      <body className="min-h-screen bg-bg text-fg antialiased selection:bg-brand-blue selection:text-white">
        {/* Google Analytics 4 (gtag.js) — site-wide visitor tracking. */}
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-0MJZL8TN5Y" strategy="afterInteractive" />
        <Script id="ga4-init" strategy="afterInteractive">
          {`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-0MJZL8TN5Y');`}
        </Script>
        {/* Skip link for keyboard / screen-reader users — only visible on focus. */}
        {/* Instant top progress bar on every navigation — gives click
            feedback so dynamic pages never feel "stuck" while loading. */}
        <NextTopLoader
          color="#1847A1"
          height={3}
          showSpinner={false}
          shadow="0 0 10px #1847A1,0 0 5px #1847A1"
          zIndex={2000}
        />
        <SkipLink />
        {/* Site chrome shows on every public page — /login, /signup and
            /dashboard drop it entirely (SiteChrome). The investor portal
            (/account) keeps it in the BROWSER but hides it inside the
            installed PWA (via .pwa-hide) so the app feels native. */}
        <SiteChrome>
          <Navbar />
        </SiteChrome>
        <main id="main" className="relative">
          {children}
        </main>
        {/* Footer + FABs — shown in the PWA too.  The install button + popup
            self-hide once the app is installed/standalone; the share rail is
            desktop-only. */}
        <SiteChrome>
          <Footer />
          <ScrollToTop />
          <WhatsAppFAB />
          <PwaInstallButton />
          <ShareSidebar />
          <PWAInstallPrompt />
        </SiteChrome>
        <RegisterSW />
        {/* Site-wide branded dialog + toast (replace native confirm/alert). */}
        <DialogHost />
        <ToastHost />
      </body>
    </html>
  );
}
